# Generated by Django 3.2.8 on 2022-06-30 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcash',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='assetcash',
            old_name='Index',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='assetcash',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='assetcash',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='assetcash',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='assetcash',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 17, 43, 32, 268122)),
        ),
        migrations.AlterField(
            model_name='assetcash',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 17, 43, 32, 268122)),
        ),
    ]
